---
abstract: 'Perl extension for minifying JavaScript code'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JavaScript-Minifier
requires:
  Exporter: 5.64_03
resources:
  bugtracker: https://github.com/zoffixznet/JavaScript-Minifier/issues
  repository: git://github.com/zoffixznet/JavaScript-Minifier.git
version: 1.09
